# Optimized pipeline settings for the preview
settings:
    pipeline:
        display_debugger: false
    lighting:
        culling_grid_size_x: 32
        culling_grid_size_y: 16
        culling_grid_slices: 32
        culling_max_distance: 80.0
        culling_slice_width: 256
        max_lights_per_cell: 32
    shadows:
        atlas_size: 4096
        max_updates: 16
